CREATE DATABASE posttest;

CREATE USER 'root'@'localhost' IDENTIFIED BY 'rootdsm';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON posttest.* TO 'root'@'localhost';